# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/ComputerNetwork/project/mto10server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/ComputerNetwork/project/mto10server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ComputerNetwork/project/mto10server/CMakeFiles /root/ComputerNetwork/project/mto10server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ComputerNetwork/project/mto10server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mto10_read

# Build rule for target.
mto10_read: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mto10_read
.PHONY : mto10_read

# fast build rule for target.
mto10_read/fast:
	$(MAKE) -f CMakeFiles/mto10_read.dir/build.make CMakeFiles/mto10_read.dir/build
.PHONY : mto10_read/fast

#=============================================================================
# Target rules for targets named mto10server

# Build rule for target.
mto10server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mto10server
.PHONY : mto10server

# fast build rule for target.
mto10server/fast:
	$(MAKE) -f CMakeFiles/mto10server.dir/build.make CMakeFiles/mto10server.dir/build
.PHONY : mto10server/fast

#=============================================================================
# Target rules for targets named database

# Build rule for target.
database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 database
.PHONY : database

# fast build rule for target.
database/fast:
	$(MAKE) -f src/CMakeFiles/database.dir/build.make src/CMakeFiles/database.dir/build
.PHONY : database/fast

#=============================================================================
# Target rules for targets named md5

# Build rule for target.
md5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 md5
.PHONY : md5

# fast build rule for target.
md5/fast:
	$(MAKE) -f src/CMakeFiles/md5.dir/build.make src/CMakeFiles/md5.dir/build
.PHONY : md5/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f src/CMakeFiles/server.dir/build.make src/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) -f src/CMakeFiles/tools.dir/build.make src/CMakeFiles/tools.dir/build
.PHONY : tools/fast

#=============================================================================
# Target rules for targets named TcpServer

# Build rule for target.
TcpServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TcpServer
.PHONY : TcpServer

# fast build rule for target.
TcpServer/fast:
	$(MAKE) -f TCP/CMakeFiles/TcpServer.dir/build.make TCP/CMakeFiles/TcpServer.dir/build
.PHONY : TcpServer/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mto10server.dir/build.make CMakeFiles/mto10server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mto10server.dir/build.make CMakeFiles/mto10server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mto10server.dir/build.make CMakeFiles/mto10server.dir/main.cpp.s
.PHONY : main.cpp.s

mto10_read.o: mto10_read.cpp.o
.PHONY : mto10_read.o

# target to build an object file
mto10_read.cpp.o:
	$(MAKE) -f CMakeFiles/mto10_read.dir/build.make CMakeFiles/mto10_read.dir/mto10_read.cpp.o
.PHONY : mto10_read.cpp.o

mto10_read.i: mto10_read.cpp.i
.PHONY : mto10_read.i

# target to preprocess a source file
mto10_read.cpp.i:
	$(MAKE) -f CMakeFiles/mto10_read.dir/build.make CMakeFiles/mto10_read.dir/mto10_read.cpp.i
.PHONY : mto10_read.cpp.i

mto10_read.s: mto10_read.cpp.s
.PHONY : mto10_read.s

# target to generate assembly for a file
mto10_read.cpp.s:
	$(MAKE) -f CMakeFiles/mto10_read.dir/build.make CMakeFiles/mto10_read.dir/mto10_read.cpp.s
.PHONY : mto10_read.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mto10_read"
	@echo "... mto10server"
	@echo "... rebuild_cache"
	@echo "... database"
	@echo "... md5"
	@echo "... server"
	@echo "... tools"
	@echo "... TcpServer"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mto10_read.o"
	@echo "... mto10_read.i"
	@echo "... mto10_read.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

